---
- name: run playbook to configure Ubuntu desktop
  hosts: localhost
  become: yes
  tasks:
  - name: Install Git
    apt:
      name: git
      state: present
      update_cache: yes

  # Install VSCode
  - name: Add MS key to trusted
    apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: present
  - name: Add MS repo to list
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      filename: vscode
      state: present
      update_cache: yes
  - name: install vscode
    apt:
      name: code
      state: present
  
  #Install Pip 3
  - name: install Python pip 3
    apt:
      name: python3-pip
      state: present
      update_cache: yes
  
  #Install Chromium browser
  - name: Install chromium browser
    apt:
      name: chromium-browser
      state: present
      update_cache: yes

  # Install restricted extras
  - name: Install restricted extras
    apt:
      name: ubuntu-restricted-extras
      state: present
      update_cache: yes
  
  # Install gnome tweak tool
  - name: Install Gnome tweak tool
    apt:
      name: gnome-tweak-tool
      state: present
      update_cache: yes
  
  # Install Conky system monitor
  - name: Install Conky
    apt:
      name: conky-all
      state: present
      update_cache: yes

  # Remove Amazon from launcher
  - name: remove Amazon from launcher
    apt:
      name: ubuntu-web-launchers
      purge: yes

  # Install docker (guide: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04)
  - name: install docker prerequisites
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

  - name: add docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      filename: dockers
      state: present
      update_cache: yes
  
  - name: install docker
    apt:
      name: docker-ce
      state: present
  
  - name: add user "{{ user }}" to group docker
    user:
      name: "{{ user }}"
      groups: docker
      append: yes

  - name: install terminator terminal
    apt:
      name: terminator
      state: present
      update_cache: yes
      
 - name: change touchpad sensitivity
   command: xinput --set-prop 13 "Synaptics Finger" 50 80 257
